/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    /*public String getGreeting() {
        return "Hello world.";
    }*/
     String name="Radhika";
    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
    System.out.println("hello");

}
}
